wpscan-api-testing1 branch
gudmdharalds-a8c/vip-go-ci-manual-testing pull request #17
Opened 2022-06-06 16:06 UTC by gudmdharalds

2022-06-14 15:04 UTC, gudmdharalds commented
# VIP Code Analysis Bot: Automated Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. WordPress VIP recommends updating the plugins before merging into the target branch.

## ℹ️  Vulnerable Plugin information
**Title**: Elementor Website Builder
**Details**: https://wordpress.org/plugins/elementor
**Installed location**: `client-mu-plugins/elementor/plugin.php`
**Version observed**: 3.3.0
**Latest version available**: 3.6.6

### 🔒  Security information
**Title**: Elementor < 3.5.6 - DOM Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/9758570b-4729-4eef-ad52-b6e922f536d6
**Severity**: 6.1/10 (MEDIUM)

**Title**: Elementor < 3.5.0 - DOM Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/9758570b-4729-4eef-ad52-b6e922f536d6
**Severity**: 5.1/10 (MEDIUM)

***

## ℹ️  Obsolete Plugin information
**Title**: Contact Form 7
**Details**: https://wordpress.org/plugins/contact-form-7/
**Installed location**: `plugins/contact-form/contact-form.php`
**Version observed**: 5.0.0.1
**Latest version available**: 5.5.6.1

***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

This bot provides automated PHP linting, [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/) along with plugin and theme security scans. For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.2</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.2</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.2</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.2</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-16 15:47 UTC, gudmdharalds-a8c commented
No issues were found to report when scanning latest commit (commit-ID: 2af02235e697572f1305931aa01032578d93235a)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-22 17:52 UTC, gudmdharalds-a8c commented
No issues were found to report when scanning latest commit (commit-ID: 2af02235e697572f1305931aa01032578d93235a)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-23 10:37 UTC, gudmdharalds-a8c commented
No issues were found to report when scanning latest commit (commit-ID: 2af02235e697572f1305931aa01032578d93235a)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-23 10:39 UTC, gudmdharalds-a8c commented
No issues were found to report when scanning latest commit (commit-ID: 2af02235e697572f1305931aa01032578d93235a)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-23 10:51 UTC, gudmdharalds-a8c commented
No issues were found to report when scanning latest commit (commit-ID: 2af02235e697572f1305931aa01032578d93235a)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-23 10:53 UTC, gudmdharalds-a8c commented
No issues were found to report when scanning latest commit (commit-ID: 2af02235e697572f1305931aa01032578d93235a)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-23 11:15 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit 2af02235e697572f1305931aa01032578d93235a ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/2af02235e697572f1305931aa01032578d93235a)).

***




<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 12:07 UTC, gudmdharalds-a8c commented
No issues were found to report when scanning latest commit (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-06-23 12:11 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 13:38 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 13:40 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 13:42 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 13:43 UTC, gudmdharalds-a8c commented
# VIP Code Analysis Bot: Automated Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. WordPress VIP recommends updating the plugins before merging into the target branch.***

Hello DollyHello DollyHello DollyNinja Forms Contact Form – The Drag and Drop Form Builder for WordPress***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 13:48 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 13:48 UTC, gudmdharalds-a8c commented
Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.***

Hello DollyHello DollyHello DollyNinja Forms Contact Form – The Drag and Drop Form Builder for WordPress***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 14:00 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

Hello Dolly***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 14:04 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 14:04 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

Hello Dolly

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 14:30 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 14:30 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information

**Plugin Name**: Hello Dolly

**Plugin URI**: https://wordpress.org/plugin/hello-dolly

**Installed location**: client-mu-plugins/my-plugin/plugin.php

**Version observed**: 1.7.0

**Latest version available**: 1.7.2

**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 14:31 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 14:31 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: client-mu-plugins/my-plugin/plugin.php
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 15:40 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: client-mu-plugins/my-plugin/plugin.php
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 15:57 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 15:59 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:01 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:02 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:06 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:06 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x31;&#x66;&#x35;&#x31;&#x32; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x31;&#x66;&#x35;&#x31;&#x32; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:09 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:09 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x6c;&#x6f;&#x63;&#x6b;&#x20; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x6c;&#x6f;&#x63;&#x6b;&#x20; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:11 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:14 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:15 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:18 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Gutenberg Ramp
**Plugin URI**: https://wordpress.org/plugin/gutenberg-ramp
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.0.0
**Latest version available**: 1.1.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/gutenberg-ramp.1.1.0.zip
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:34 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Gutenberg Ramp
**Plugin URI**: https://wordpress.org/plugin/gutenberg-ramp
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.0.0
**Latest version available**: 1.1.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/gutenberg-ramp.1.1.0.zip
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 16:43 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 18:00 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-23 18:00 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Gutenberg Ramp
**Plugin URI**: https://wordpress.org/plugin/gutenberg-ramp
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.0.0
**Latest version available**: 1.1.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/gutenberg-ramp.1.1.0.zip
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 11:59 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 11:59 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Gutenberg Ramp
**Plugin URI**: https://wordpress.org/plugin/gutenberg-ramp
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.0.0
**Latest version available**: 1.1.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/gutenberg-ramp.1.1.0.zip
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 12:02 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Gutenberg Ramp
**Plugin URI**: https://wordpress.org/plugin/gutenberg-ramp
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.0.0
**Latest version available**: 1.1.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/gutenberg-ramp.1.1.0.zip
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 12:05 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 12:05 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Gutenberg Ramp
**Plugin URI**: https://wordpress.org/plugin/gutenberg-ramp
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.0.0
**Latest version available**: 1.1.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/gutenberg-ramp.1.1.0.zip
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 12:06 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 12:06 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugin/hello-dolly
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.7.0
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip


### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.1 - Test vulnerability
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Hello Dolly &lt; 1.7.2 - Test vulnerability #2
**Details**: https://wpscan.com/vulnerability/14007aca-9172-4496-b921-0074deb20bc2
**Severity**:  6.1/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Gutenberg Ramp
**Plugin URI**: https://wordpress.org/plugin/gutenberg-ramp
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.0.0
**Latest version available**: 1.1.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/gutenberg-ramp.1.1.0.zip
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 12:07 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 12:07 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34.1 - Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8.2 - NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.4 - Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.8wp - Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.5 - Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.11 - Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testl [...]

2022-06-24 15:49 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 15:49 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/api/v3/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34.1 - Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/api/v3/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/api/v3/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/api/v3/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/api/v3/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/api/v3/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8.2 - NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.4 - Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/api/v3/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.8wp - Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/api/v3/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.5 - Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/api/v3/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.11 - Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/api/v3/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code> [...]

2022-06-24 16:25 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: &lt;code&gt;syntax error, unexpected &#039;;&#039;&lt;/code&gt;


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: &lt;code&gt;syntax error, unexpected token &quot;;&quot;&lt;/code&gt;


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 16:25 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34.1 - Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/api/v3/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/api/v3/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/api/v3/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8.2 - NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.4 - Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/api/v3/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.8wp - Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.5 - Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/api/v3/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.11 - Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/api/v3/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only [...]

2022-06-24 16:32 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 16:32 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34.1 - Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/api/v3/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/api/v3/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/api/v3/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8.2 - NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.4 - Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/api/v3/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.8wp - Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.5 - Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/api/v3/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.11 - Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/api/v3/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only [...]

2022-06-24 16:35 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 16:51 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34.1 - Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/api/v3/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/api/v3/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/api/v3/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8.2 - NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.4 - Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/api/v3/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.8wp - Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.5 - Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/api/v3/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.11 - Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/api/v3/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only [...]

2022-06-24 17:07 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 17:07 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34.1 - Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/api/v3/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/api/v3/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/api/v3/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8.2 - NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.4 - Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/api/v3/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.8wp - Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/api/v3/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.5 - Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/api/v3/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/api/v3/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.11 - Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/api/v3/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only [...]

2022-06-24 17:34 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 17:36 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 17:38 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 17:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34.1 - Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.4.34 - Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8 - Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.8.2 - NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.4 - Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.8wp - Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.5.5 - Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.10 - Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress &lt; 3.6.11 - Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testl [...]

2022-06-24 17:43 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-24 17:43 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress – Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enable [...]

2022-06-24 17:46 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS seve [...]

2022-06-28 16:33 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:37 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:37 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:37 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete themes being submitted in this pull request. Updating the themes before merging into the target branch is strongly recommended.

***

##### Incorrect themes? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:40 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:42 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:46 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:46 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS seve [...]

2022-06-28 16:47 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-28 16:47 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS seve [...]

2022-06-28 17:52 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-29 12:53 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-29 12:53 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS seve [...]

2022-06-30 18:22 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-06-30 18:22 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS seve [...]

2022-07-01 15:09 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-01 16:15 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-01 16:15 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS seve [...]

2022-07-01 16:52 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-01 16:52 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.6.2</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approval DB enabled:
<code>false</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS seve [...]

2022-07-04 23:10 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 12:59 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 15:20 UTC, gudmdharalds-a8c commented
Invalid PHPCS sniff(s) specified in options or options file. Those have been ignored temporarily. Please update the options so that scanning can continue as expected. <br />

* Option name: `--phpcs-sniffs-exclude`
* Invalid sniff(s): `MySource.CSS.BrowserSpecificStyles`
 (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3).

2022-07-05 15:20 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 15:21 UTC, gudmdharalds-a8c commented
Invalid PHPCS sniff(s) specified in options or options file. Those have been ignored temporarily. Please update the options so that scanning can continue as expected. <br />

* Option name: `--phpcs-sniffs-exclude`
* Invalid sniff(s): `MySource.CSS.BrowserSpecificStyles`
 (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3).

2022-07-05 15:23 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li><code>MySource.CSS.BrowserSpecificStyles</code></li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 15:24 UTC, gudmdharalds-a8c commented
Invalid PHPCS sniff(s) specified in options or options file. Those have been ignored temporarily. Please update the options so that scanning can continue as expected. <br />

* Option name: `--phpcs-sniffs-include`
* Invalid sniff(s): `MySource.CSS.BrowserSpecificStyles`
 (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3).

2022-07-05 15:24 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 17:32 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 18:32 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 23:46 UTC, gudmdharalds-a8c commented
Invalid PHPCS sniff(s) specified in options or options file. Those have been ignored temporarily. Please update the options so that scanning can continue as expected. <br />

* Option name: `--phpcs-sniffs-include`
* Invalid sniff(s): `PHPCSUtils`
 (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3).

2022-07-05 23:46 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 23:48 UTC, gudmdharalds-a8c commented
Invalid PHPCS sniff(s) specified in options or options file. Those have been ignored temporarily. Please update the options so that scanning can continue as expected. <br />

* Option name: `--phpcs-sniffs-include`
* Invalid sniff(s): `PHPCS23Utils`
 (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3).

2022-07-05 23:48 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 23:49 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li><code>PHPCS23Utils.Load.LoadUtils</code></li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 23:50 UTC, gudmdharalds-a8c commented
Invalid PHPCS sniff(s) specified in options or options file. Those have been ignored temporarily. Please update the options so that scanning can continue as expected. <br />

* Option name: `--phpcs-sniffs-include`
* Invalid sniff(s): `PHPCS23Utils.Load.LoadUtils2`
 (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3).

2022-07-05 23:51 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 23:53 UTC, gudmdharalds-a8c commented
Invalid PHPCS sniff(s) specified in options or options file. Those have been ignored temporarily. Please update the options so that scanning can continue as expected. <br />

* Option name: `--phpcs-sniffs-exclude`
* Invalid sniff(s): `PHPCS23Utils.Load.LoadUtils2`
 (commit-ID: ee2668e67c0b414856af87243ed35b648a56f8b3).

2022-07-05 23:53 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-05 23:53 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>PHPCS23Utils.Load.LoadUtils</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:10 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:10 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used: [...]

2022-07-06 15:17 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fplugin.php/client-mu-plugins%2Fmy-plugin%2Fplugin.php#L1)).`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins%2Fhello%2Fhello.php/plugins%2Fhello%2Fhello.php#L1)).`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins%2Fhello2%2Fhello2.php/plugins%2Fhello2%2Fhello2.php#L1)).`
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins%2Fninja-forms%2Fninja-forms.php/plugins%2Fninja-forms%2Fninja-forms.php#L1)).`
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><c [...]

2022-07-06 15:20 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:22 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:22 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fplugin.php#L1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins%2Fhello%2Fhello.php#L1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins%2Fhello2%2Fhello2.php#L1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins%2Fninja-forms%2Fninja-forms.php#L1)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code [...]

2022-07-06 15:32 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:32 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php#L1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php#L1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php#L1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php#L1)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code> [...]

2022-07-06 15:43 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:43 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></ [...]

2022-07-06 15:45 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></ [...]

2022-07-06 15:46 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 15:46 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (MEDIUM)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (MEDIUM)
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></ [...]

2022-07-06 16:52 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 16:55 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (UNKNOWN
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (UNKNOWN
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></ [...]

2022-07-06 16:58 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 16:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (LOW) 
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li [...]

2022-07-06 17:23 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-06 17:23 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

Automated scanning has identified one or more insecure or obsolete plugins being submitted in this pull request. Updating the plugins before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  6.1/10 (LOW) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  6.1/10 (LOW) 
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li [...]

2022-07-07 13:21 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 15:13 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 15:45 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated scanning.



PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 16:08 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated scanning.



PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 16:11 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated scanning.



PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 16:19 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 16:19 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  4.5/10 (MEDIUM) 
***

##### Incorrect plugins? [Learn how to prevent false-positive matches.](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches)

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><l [...]

2022-07-07 16:33 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit ee2668e67c0b414856af87243ed35b648a56f8b3 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 16:33 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/ee2668e67c0b414856af87243ed35b648a56f8b3/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**:  4.5/10 (MEDIUM) 
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**:  4.5/10 (MEDIUM) 
***

Incorrect plugins? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).&lt;/a&gt;

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></l [...]

2022-07-07 23:11 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-07 23:11 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugins? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove [...]

2022-07-08 13:26 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-08 13:26 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugins? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove [...]

2022-07-08 13:46 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/fa8f0d49a7e082422da10ebd9e1787e2ac4fb03e/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-08 18:08 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-08 18:08 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugins? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove [...]

2022-07-08 18:12 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-08 18:12 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-08 18:14 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-08 18:14 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-08 18:17 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-08 18:17 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-08 18:28 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 12:56 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 12:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-12 13:00 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:03 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:03 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-12 13:13 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:13 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-12 13:16 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:16 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-12 13:18 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:19 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-12 13:21 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:29 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:32 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit c8a50e2396e8106838afca2d15e75b3de2f8e9e8 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/c8a50e2396e8106838afca2d15e75b3de2f8e9e8)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/c8a50e2396e8106838afca2d15e75b3de2f8e9e8/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:38 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoappro [...]

2022-07-12 13:42 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:54 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:55 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:56 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 13:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

Incorrect plugin(s)? [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 14:25 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 14:25 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 14:28 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 14:28 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 19:59 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 19:59 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:01 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:01 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:03 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:03 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:07 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:07 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:11 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:12 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:14 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:16 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:16 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:20 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:22 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:24 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:24 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:27 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:27 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:40 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:40 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:42 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 20:42 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 21:45 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 21:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 21:48 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 21:48 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 21:54 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 21:54 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:37 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:37 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:42 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:42 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:42 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:46 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:46 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:54 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:56 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:58 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 22:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 23:11 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 23:11 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 23:20 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 23:20 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-12 23:36 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 11:46 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit e65d413c372e29666085788d2a9a6c6952ad2985 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 11:46 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/e65d413c372e29666085788d2a9a6c6952ad2985/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:30 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9b5e23d3b1a17f32093e2d0c2a1492bd20852174 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9b5e23d3b1a17f32093e2d0c2a1492bd20852174)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9b5e23d3b1a17f32093e2d0c2a1492bd20852174/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9b5e23d3b1a17f32093e2d0c2a1492bd20852174/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:30 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9b5e23d3b1a17f32093e2d0c2a1492bd20852174/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin-to-be-skipped.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9b5e23d3b1a17f32093e2d0c2a1492bd20852174/plugins/hello-dolly-plugin-to-be-skipped.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9b5e23d3b1a17f32093e2d0c2a1492bd20852174/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9b5e23d3b1a17f32093e2d0c2a1492bd20852174/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9b5e23d3b1a17f32093e2d0c2a1492bd20852174/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:33 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 6071d46a2feceb2e04fb40f6cee649e500b097a6 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:33 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin-to-be-skipped.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin-to-be-skipped.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:34 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin-to-be-skipped.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin-to-be-skipped.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:36 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 6071d46a2feceb2e04fb40f6cee649e500b097a6 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:36 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin-to-be-skipped.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin-to-be-skipped.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin-to-be-skipped.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin-to-be-skipped.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/6071d46a2feceb2e04fb40f6cee649e500b097a6/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:40 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit cf5735f11e7f894a40af088119e5a32b9dffcdad ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/cf5735f11e7f894a40af088119e5a32b9dffcdad)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/cf5735f11e7f894a40af088119e5a32b9dffcdad/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/cf5735f11e7f894a40af088119e5a32b9dffcdad/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 14:55 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.0
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 22:49 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-07-13 22:49 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.12.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.12
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.12.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.3</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options fi [...]

2022-09-06 17:45 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-06 17:45 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 24 errors 

:warning: 4 warnings 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>




Posting will continue in further review(s)

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on client-mu-plugins/my-plugin/path1/test2.php
> +echo ;
:no_entry_sign: **Error( severity 5 )**: Space found before semicolon; expected &quot;echo;&quot; but found &quot;echo ;&quot; (*Squiz.WhiteSpace.SemicolonSpacing.Incorrect*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello/docs/file.php
> +// Test
:no_entry_sign: **Error( severity 5 )**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-06 17:45 UTC, gudmdharalds-a8c requested changes
Previous scan continued.

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Plugin Name: Popup Builder
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Plugin URI: https://popup-builder.com
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Description: The most complete popup plugin. Html, image, iframe, shortcode, video and many other popup types. Manage popup dimensions, effects, themes and more.
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Version: 4.0.0
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Author: Sygnoos
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Author URI: https://sygnoos.com
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* License: GPLv2
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Text Domain:  popup-builder
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Domain Path:  /languages/
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:45 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +*/
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-06 17:50 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-06 17:50 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-06 17:50 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 17:50 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 17:50 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 17:50 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 18:15 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-06 18:15 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</su [...]

2022-09-06 18:16 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-06 18:16 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 18:16 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 18:16 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-06 18:16 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 15:32 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 15:32 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 15:32 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 15:32 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 15:32 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 15:32 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 16:42 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 16:42 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 16:42 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 16:42 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 16:42 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 16:42 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:35 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 17:35 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 17:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:35 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:35 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:38 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 17:38 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 17:38 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:38 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:38 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:38 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:55 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 17:55 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 17:55 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:55 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:55 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 17:55 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:05 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 18:05 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 18:05 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:05 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:05 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:05 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:14 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 18:14 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 18:14 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:14 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:14 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:14 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:20 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 18:20 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 18:20 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:20 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:20 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:20 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:22 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 18:22 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 18:22 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:22 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:22 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:22 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:24 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 18:24 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 18:24 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:24 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:24 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:24 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:26 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 18:26 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 18:26 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:26 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:26 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 18:26 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 21:33 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 21:33 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 21:33 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 21:33 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 21:33 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 21:33 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:08 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 22:08 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 22:08 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:08 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:08 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:08 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:22 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 22:22 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 22:22 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:22 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:22 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:22 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:29 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 22:29 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 22:29 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:29 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:29 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:29 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:43 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 22:43 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: http://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: http://ninjaforms.com/?utm_source=Ninja+Forms+Plugin&amp;utm_medium=readme
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://popup-builder.com
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</su [...]

2022-09-07 22:44 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 22:44 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 22:44 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:44 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:44 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:44 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:49 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 22:49 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<t [...]

2022-09-07 22:49 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 22:49 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 22:49 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:49 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:49 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 22:49 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 23:09 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 23:09 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 24 errors 

:warning: 4 warnings 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>




Posting will continue in further review(s)

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on client-mu-plugins/my-plugin/path1/test2.php
> +echo ;
:no_entry_sign: **Error( severity 5 )**: Space found before semicolon; expected &quot;echo;&quot; but found &quot;echo ;&quot; (*Squiz.WhiteSpace.SemicolonSpacing.Incorrect*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello/docs/file.php
> +// Test
:no_entry_sign: **Error( severity 5 )**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-07 23:09 UTC, gudmdharalds-a8c requested changes
Previous scan continued.

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Plugin Name: Popup Builder
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Plugin URI: https://popup-builder.com
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Description: The most complete popup plugin. Html, image, iframe, shortcode, video and many other popup types. Manage popup dimensions, effects, themes and more.
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Version: 4.0.0
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Author: Sygnoos
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Author URI: https://sygnoos.com
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* License: GPLv2
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Text Domain:  popup-builder
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Domain Path:  /languages/
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:09 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +*/
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-07 23:13 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 23:13 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 23:13 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-07 23:13 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-07 23:13 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:13 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:13 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-07 23:13 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:07 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-08 15:07 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 11 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-08 15:07 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:07 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:07 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:07 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Version: 4.0.0
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-08 15:07 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Author URI: https://sygnoos.com
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-08 15:07 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* License: GPLv2
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-08 15:07 UTC, gudmdharalds-a8c commented on plugins/popup-builder/popup-builder.php
> +* Text Domain:  popup-builder
:no_entry_sign: **Error( severity 5 )**: Expected 1 space(s) before asterisk; 0 found (*Squiz.Commenting.DocCommentAlignment.SpaceBeforeStar*).

2022-09-08 15:10 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-08 15:10 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-08 15:10 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:10 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:10 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:10 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:11 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-08 15:11 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-08 15:11 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:11 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:11 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:11 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:26 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-08 15:26 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-08 15:26 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-08 15:26 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:26 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:26 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-08 15:26 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 18:43 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-09 18:43 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-09 18:43 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-09 18:43 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-09 18:43 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 18:43 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 18:43 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 18:43 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 19:34 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-09 19:34 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-09 19:34 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-09 19:34 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-09 19:34 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 19:34 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 19:34 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-09 19:34 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 11:36 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 11:36 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<t [...]

2022-09-12 11:36 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 11:36 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-12 11:36 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 11:36 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:11 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 13:11 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 13:11 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 13:11 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-12 13:11 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:11 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:11 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:11 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:14 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 13:14 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 13:14 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/9004ebcc61e3be0f95ff7ab1c57e3f98505fc6e1/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 13:14 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 4 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-12 13:14 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:14 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:30 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-12 13:30 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>tru [...]

2022-09-12 13:30 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 5 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-12 13:30 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:30 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 13:30 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 14:31 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>tru [...]

2022-09-12 14:31 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 5 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-12 14:31 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 14:31 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 14:31 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 14:31 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-12 14:31 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:56 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:56 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:57 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-14 19:57 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 5 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

2022-09-14 19:57 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:57 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:57 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:57 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:57 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:59 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-14 19:59 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 5 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

2022-09-14 19:59 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:59 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:59 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:59 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 19:59 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:18 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-14 20:18 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 5 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

2022-09-14 20:18 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:18 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:18 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:18 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:18 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:19 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-14 20:19 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 5 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

2022-09-14 20:19 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:19 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:19 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:19 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:19 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:34 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 2 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

2022-09-14 20:34 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:34 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-14 20:35 UTC, gudmdharalds-a8c commented
Total number of active review comments per pull request has been reached and some comments might not appear as a result. Please resolve some issues to see more (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876).

2022-09-14 20:57 UTC, gudmdharalds-a8c commented
Total number of active review comments per pull request has been reached and some comments might not appear as a result. Please resolve some issues to see more (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876).

2022-09-14 20:57 UTC, gudmdharalds-a8c commented
Scanning latest commit did not yield any new issues. Please have a look at older feedback still existing (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>false</code></p></td>
</tr>
</table>
</details>

2022-09-16 17:29 UTC, gudmdharalds-a8c commented
Total number of active review comments per pull request has been reached and some comments might not appear as a result. Please resolve some issues to see more (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876).

2022-09-16 17:29 UTC, gudmdharalds-a8c commented
Scanning latest commit did not yield any new issues. Please have a look at older feedback still existing (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-16 17:33 UTC, gudmdharalds-a8c commented
Total number of active review comments per pull request has been reached and some comments might not appear as a result. Please resolve some issues to see more (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876).

2022-09-16 17:33 UTC, gudmdharalds-a8c commented
Scanning latest commit did not yield any new issues. Please have a look at older feedback still existing (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-16 19:28 UTC, gudmdharalds-a8c commented
Total number of active review comments per pull request has been reached and some comments might not appear as a result. Please resolve some issues to see more (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876).

2022-09-16 19:28 UTC, gudmdharalds-a8c commented
Scanning latest commit did not yield any new issues. Please have a look at older feedback still existing (commit-ID: 1b9eaf79b7ae87d55df06501bfd433df5a083876)

***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).




***


<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-16 19:35 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:35 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-16 19:35 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:35 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 6 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-16 19:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-16 19:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-16 19:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-16 19:35 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-16 19:35 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-16 19:35 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-16 19:38 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-16 19:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:41 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:41 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
***Severity***: 8.7
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
***Severity***: 8.7
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***Severity***: 8.7
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
***Severity***: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***Severity***: 8.7
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/ [...]

2022-09-16 19:41 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:51 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:51 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**: 8.7
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**: 8.7
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
**Severity**: 8.7
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
**Severity**: 8.7
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
**Severity**: 8.7
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7 [...]

2022-09-16 19:51 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:53 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:53 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
**Severity**: 8.7/10 (CRITICAL)
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
**Severity**: 8.7/10 (CRITICAL)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
**Severity**: 8.7/10 (CRITICAL)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139; [...]

2022-09-16 19:53 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:56 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 19:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
**Severity**: 8.7/10 (UNKNOWN)
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
**Severity**: 8.7/10 (UNKNOWN)
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
**Severity**: 8.7/10 (UNKNOWN)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsol [...]

2022-09-16 19:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 20:02 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 20:02 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>tru [...]

2022-09-16 20:02 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 20:05 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 20:05 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Vuln1
**Details**: https://wpscan.com/vulnerability/test1
**Severity**: 8.7/10 (NONE)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p [...]

2022-09-16 20:05 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 20:38 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-16 20:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Vuln1
**Details**: https://wpscan.com/vulnerability/test1
**Severity**: 8.7/10 (HIGH)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p [...]

2022-09-16 20:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-19 14:10 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-19 14:10 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Vuln1
**Details**: https://wpscan.com/vulnerability/test1
**Severity**: 8.7/10 (HIGH)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p [...]

2022-09-19 14:10 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-19 14:10 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 6 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-19 14:10 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-19 14:10 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-19 14:10 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-19 14:10 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-19 14:10 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-19 14:10 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-21 17:08 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-21 20:00 UTC, gudmdharalds-a8c commented
**PHP Syntax Errors Found**


Scan performed on the code at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/path1/test2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/path1/test2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-21 20:06 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-21 20:06 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-21 20:07 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:32 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:32 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-23 18:33 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:45 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-23 18:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:47 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:47 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-23 18:47 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:49 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:49 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-23 18:49 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:50 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:50 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-23 18:50 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:58 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manag [...]

2022-09-23 18:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 18:58 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 1 error 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-23 18:58 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-23 19:29 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 19:29 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>tru [...]

2022-09-23 19:29 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 19:34 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 19:37 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 19:37 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin/plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin/plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello-dolly-plugin.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello-dolly-plugin.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello/hello.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello/hello.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2/hello2.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2/hello2.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms/ninja-forms.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms/ninja-forms.php)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder/popup-builder.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder/popup-builder.php)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1/hello3/hello3.php` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1/hello3/hello3.php)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>tru [...]

2022-09-23 19:37 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 19:44 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-23 19:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Di [...]

2022-09-23 19:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 16:31 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 16:31 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Di [...]

2022-09-26 16:31 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 16:37 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 16:40 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 17:22 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 17:25 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 17:25 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Di [...]

2022-09-26 17:25 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 17:32 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 19:59 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>https://wpscan.com/api/v3</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 19:59 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>https://wpscan.com/api/v3</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</ [...]

2022-09-26 19:59 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>https://wpscan.com/api/v3</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 20:51 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 20:51 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Di [...]

2022-09-26 20:51 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 21:10 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting.We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 21:10 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form &ndash; The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34.1 - Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.4.34 - CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.5.8 - Unprotected REST-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.5.8.2 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.4 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.8 - Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &lt; 3.5.5 - Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.10 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &lt; 3.6.11 - Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &lt; 3.6.13 - Admin+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder &ndash; Create highly converting, mobile friendly marketing popups.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.0.7 - Admin+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - SQL Injection to Reflected Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.11 - Admin+ Stored Cross-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.12 - Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &lt; 4.1.1 - Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs- [...]

2022-09-26 21:10 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 21:55 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-26 21:55 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress\.org/plugins/ninja\-forms/
**Installed location**: `plugins/ninja\-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads\.wordpress\.org/plugin/ninja\-forms\.3\.6\.14\.zip


### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan\.com/vulnerability/55fde9fa\-f6cd\-4546\-bee8\-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan\.com/vulnerability/dfa32afa\-c6de\-4237\-a9f2\-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan\.com/vulnerability/6147acf5\-e43f\-47e6\-ab56\-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan\.com/vulnerability/b531fb65\-a8ff\-4150\-a9a1\-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan\.com/vulnerability/606973aa\-cf5d\-43a7\-9ef5\-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan\.com/vulnerability/b9f6dad5\-2293\-482f\-9ee6\-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms \< 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan\.com/vulnerability/e383fae6\-e0da\-4aba\-bb62\-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan\.com/vulnerability/55008a42\-eb56\-436c\-bce0\-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan\.com/vulnerability/cec7d366\-7663\-4b83\-9640\-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms \< 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan\.com/vulnerability/ba6fa3d6\-e3f7\-449a\-bd78\-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan\.com/vulnerability/323d5fd0\-abe8\-44ef\-9127\-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan\.com/vulnerability/795acab2\-f621\-4662\-834b\-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms \< 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan\.com/vulnerability/8843d66b\-e895\-4336\-afda\-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms \< 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan\.com/vulnerability/255b98ba\-5da9\-4424\-a7e9\-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress\.org/plugins/popup\-builder/
**Installed location**: `plugins/popup\-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads\.wordpress\.org/plugin/popup\-builder\.4\.1\.13\.zip


### &#x1f512; Security information
**Title**: Popup Builder \< 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan\.com/vulnerability/0f90f10c\-4b0a\-46da\-ac1f\-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder \< 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan\.com/vulnerability/22facac2\-52f4\-4e5f\-be59\-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder \< 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan\.com/vulnerability/0d2bbbaf\-fbfd\-4921\-ba4e\-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder \< 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan\.com/vulnerability/68af14ef\-ca66\-40d6\-a1e5\-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder \< 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan\.com/vulnerability/ca0f90ef\-af9a\-4628\-9032\-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder \< 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan\.com/vulnerability/f0e39557\-fe07\-4df0\-8cc3\-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress\.org/plugins/hello\-dolly/
**Installed location**: `client\-mu\-plugins/my\-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads\.wordpress\.org/plugin/hello\-dolly\.1\.7\.2\.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress\.org/plugins/hello\-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads\.wordpress\.org/plugin/hello\-dolly\.1\.7\.2\.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress\.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads\.wordpress\.org/plugin/hello\-dolly\.1\.7\.2\.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress\.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads\.wordpress\.org/plugin/hello\-dolly\.1\.7\.2\.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress\.org/plugins/hello\-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads\.wordpress\.org/plugin/hello\-dolly\.1\.7\.2\.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-fal [...]

2022-09-26 21:55 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress\.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads\.wordpress\.org/theme/twentytwentyone\.1\.6\.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:41 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:41 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja\-forms/
**Installed location**: `plugins/ninja\-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja\-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa\-f6cd\-4546\-bee8\-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa\-c6de\-4237\-a9f2\-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5\-e43f\-47e6\-ab56\-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65\-a8ff\-4150\-a9a1\-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa\-cf5d\-43a7\-9ef5\-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5\-2293\-482f\-9ee6\-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &\#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6\-e0da\-4aba\-bb62\-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42\-eb56\-436c\-bce0\-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366\-7663\-4b83\-9640\-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &\#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6\-e3f7\-449a\-bd78\-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0\-abe8\-44ef\-9127\-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2\-f621\-4662\-834b\-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &\#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b\-e895\-4336\-afda\-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &\#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba\-5da9\-4424\-a7e9\-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup\-builder/
**Installed location**: `plugins/popup\-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup\-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &\#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c\-4b0a\-46da\-ac1f\-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &\#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2\-52f4\-4e5f\-be59\-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &\#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf\-fbfd\-4921\-ba4e\-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &\#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef\-ca66\-40d6\-a1e5\-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &\#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef\-af9a\-4628\-9032\-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &\#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557\-fe07\-4df0\-8cc3\-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `client\-mu\-plugins/my\-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-pre [...]

2022-09-27 00:41 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:45 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `client\-mu\-plugins/my\-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja\-forms/
**Installed location**: `plugins/ninja\-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja\-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup\-builder/
**Installed location**: `plugins/popup\-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup\-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</co [...]

2022-09-27 00:45 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:50 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:50 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `client\-mu\-plugins/my\-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja\-forms/
**Installed location**: `plugins/ninja\-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja\-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup\-builder/
**Installed location**: `plugins/popup\-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup\-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello\-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello\-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</co [...]

2022-09-27 00:50 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:58 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 00:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Di [...]

2022-09-27 00:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 01:02 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 01:03 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &\#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3< [...]

2022-09-27 01:10 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 12:18 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 12:18 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder)).
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms)).
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1)).
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</ [...]

2022-09-27 12:18 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone)).
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false-positive matches](https://docs.wpvip.com/technical-references/codebase-manager/#h-preventing-false-positive-plugin-matches).

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 12:48 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 12:48 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

\*\*\*Incorrect plugin(s)?\*\*\* [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.c [...]

2022-09-27 12:48 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

\*\*\*Incorrect theme(s)?\*\*\* [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 12:51 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 12:51 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 12:59 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 12:59 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 12:59 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:40 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:40 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 13:42 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:43 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:45 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:48 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:50 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:50 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 13:53 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:53 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 13:53 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:56 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 13:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 13:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:08 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:11 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:11 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 18:11 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:18 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:18 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 18:18 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:21 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:21 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 18:57 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-27 18:57 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Test &#60; 0\.60
**Details**: https://wpscan.com/vulnerability/0x100
**Severity**: 6.7/10 (MEDIUM)
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api [...]

2022-09-27 18:57 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-28 14:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-28 14:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-28 14:35 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-28 14:35 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-28 14:35 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-28 14:35 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-28 14:43 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP  [...]

2022-09-28 14:43 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-28 14:48 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP  [...]

2022-09-28 14:48 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.2.6</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-29 19:56 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-29 19:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.13.zip


### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP  [...]

2022-09-29 19:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-09-29 19:56 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 6 errors 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-09-29 19:56 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-29 19:56 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-09-29 19:56 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-29 19:56 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-29 19:56 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-09-29 19:56 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 12:51 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 12:52 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 12:52 UTC, gudmdharalds-a8c requested changes
.

2022-10-05 12:52 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 12:52 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-10-05 12:52 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 12:52 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 12:52 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 12:52 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 13:02 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:03 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:06 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 13:06 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:17 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:25 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:25 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 13:25 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:36 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:36 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 13:36 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:38 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 13:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:52 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:53 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 13:53 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:56 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 13:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 13:56 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 14:01 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit 1b9eaf79b7ae87d55df06501bfd433df5a083876 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 14:01 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 14:01 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 14:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 14:38 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/1b9eaf79b7ae87d55df06501bfd433df5a083876/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 16:58 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit abfe9c2e0e3b1f5c4ed825df473587ae68984468 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 16:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Ninja Forms
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Popup builder
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.13
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
 [...]

2022-10-05 16:58 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-05 16:58 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 9 errors 

:warning: 1 warning 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.0</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-10-05 16:58 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit abfe9c2e0e3b1f5c4ed825df473587ae68984468 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-06 19:17 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip


### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP  [...]

2022-10-06 19:17 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-06 19:17 UTC, gudmdharalds-a8c requested changes
# Code analysis identified issues
VIP Code Analysis Bot has identified potential problems in this pull request during automated scanning. We recommend reviewing the issues noted and that they are resolved.

**phpcs** scanning turned up:

:no_entry_sign: 9 errors 

:warning: 1 warning 


***


This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).



<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin-to-be-skipped.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/hello-dolly-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/hello/hello.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/hello2/hello2.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +function hello_dolly() {
:no_entry_sign: **Error( severity 5 )**: Missing doc comment for function hello_dolly() (*Squiz.Commenting.FunctionComment.Missing*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +  hello_dolly_get_lyric();
:warning: **Warning( severity 5 )**: Found precision alignment of 2 spaces (*WordPress.WhiteSpace.PrecisionAlignment.Found*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/not-a-plugin/not-a-plugin.php
> +  hello_dolly_get_lyric();
:no_entry_sign: **Error( severity 5 )**: Line indented incorrectly; expected at least 1 tabs, found 2 spaces (*Generic.WhiteSpace.ScopeIndent.Incorrect*).

2022-10-06 19:17 UTC, gudmdharalds-a8c commented on plugins/subdir1/hello3/hello3.php
> +function hello_dolly_get_lyric() {
:no_entry_sign: **Error( severity 5 )**: You must use &quot;/**&quot; style comments for a function comment (*Squiz.Commenting.FunctionComment.WrongStyle*).

2022-10-06 19:18 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit abfe9c2e0e3b1f5c4ed825df473587ae68984468 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-06 19:18 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip


### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP  [...]

2022-10-06 19:18 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-06 19:20 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit abfe9c2e0e3b1f5c4ed825df473587ae68984468 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-06 19:20 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip


### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP  [...]

2022-10-06 19:20 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-06 19:22 UTC, gudmdharalds-a8c commented
# PHP Syntax Errors Found
VIP Code Analysis Bot has identified PHP syntax errors during automated linting. We recommend reviewing the issues noted and that they are resolved.


PHP linting performed at commit abfe9c2e0e3b1f5c4ed825df473587ae68984468 ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468)).

***

**Error**: Linting with PHP 7.4 turned up: <code>syntax error, unexpected &#039;;&#039;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3


***

**Error**: Linting with PHP 8.1 turned up: <code>syntax error, unexpected token &quot;;&quot;</code>


https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/blob/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins%2Fmy-plugin%2Fpath1%2Ftest2.php#L3

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-06 19:23 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete plugin(s) being submitted or altered in this pull request. Updating the plugin(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Ninja Forms Contact Form – The Drag and Drop Form Builder for WordPress
**Plugin URI**: https://wordpress.org/plugins/ninja-forms/
**Installed location**: `plugins/ninja-forms` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/ninja-forms))
**Version observed**: 3.4.32
**Latest version available**: 3.6.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/ninja-forms.3.6.14.zip


### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Authenticated SendWP Plugin Installation and Client Secret Key Disclosure
**Details**: https://wpscan.com/vulnerability/55fde9fa-f6cd-4546-bee8-4acc628251c2
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34\.1 \- Authenticated OAuth Connection Key Disclosure
**Details**: https://wpscan.com/vulnerability/dfa32afa-c6de-4237-a9f2-709843dcda89
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- Administrator Open Redirect
**Details**: https://wpscan.com/vulnerability/6147acf5-e43f-47e6-ab56-c9c8be584818
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.4\.34 \- CSRF to OAuth Service Disconnection
**Details**: https://wpscan.com/vulnerability/b531fb65-a8ff-4150-a9a1-2a62a3c00bd6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Sensitive Information Disclosure
**Details**: https://wpscan.com/vulnerability/606973aa-cf5d-43a7-9ef5-faa7f9af5318
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.5\.8 \- Unprotected REST\-API to Email Injection
**Details**: https://wpscan.com/vulnerability/b9f6dad5-2293-482f-9ee6-dc8b4c713b80
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.5\.8\.2 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/e383fae6-e0da-4aba-bb62-adf51c01bf8d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.4 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/55008a42-eb56-436c-bce0-10ee616d0495
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.8 \- Unauthenticated Email Address Disclosure
**Details**: https://wpscan.com/vulnerability/cec7d366-7663-4b83-9640-a58f2fcf5e41
### &#x1f512; Security information
**Title**: Nina Forms &#60; 3\.5\.5 \- Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/ba6fa3d6-e3f7-449a-bd78-d57c26a67aa6
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting via Import
**Details**: https://wpscan.com/vulnerability/323d5fd0-abe8-44ef-9127-eea6fd4f3f3d
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.10 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/795acab2-f621-4662-834b-ebb6205ef7de
### &#x1f512; Security information
**Title**: Ninja Forms &#60; 3\.6\.11 \- Unauthenticated PHP Object Injection
**Details**: https://wpscan.com/vulnerability/8843d66b-e895-4336-afda-00b99442cdc1
### &#x1f512; Security information
**Title**: NinjaForms &#60; 3\.6\.13 \- Admin\+ PHP Objection Injection
**Details**: https://wpscan.com/vulnerability/255b98ba-5da9-4424-a7e9-c438d8905864
***

## &#x2139;&#xfe0f;&#x20; Vulnerable Plugin information
**Plugin Name**: Popup Builder – Create highly converting, mobile friendly marketing popups\.
**Plugin URI**: https://wordpress.org/plugins/popup-builder/
**Installed location**: `plugins/popup-builder` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/popup-builder))
**Version observed**: 4.0.0
**Latest version available**: 4.1.14
**Latest version download URI**: https://downloads.wordpress.org/plugin/popup-builder.4.1.14.zip


### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- LFI to RCE
**Details**: https://wpscan.com/vulnerability/0f90f10c-4b0a-46da-ac1f-aa6a03312132
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.0\.7 \- Admin\+ SQL Injection
**Details**: https://wpscan.com/vulnerability/22facac2-52f4-4e5f-be59-1d2934b260d9
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- SQL Injection to Reflected Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/0d2bbbaf-fbfd-4921-ba4e-684e2e77e816
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.11 \- Admin\+ Stored Cross\-Site Scripting
**Details**: https://wpscan.com/vulnerability/68af14ef-ca66-40d6-a1e5-09f74e2cd971
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.12 \- Settings Update via CSRF
**Details**: https://wpscan.com/vulnerability/ca0f90ef-af9a-4628-9032-b536a0e6cd9b
### &#x1f512; Security information
**Title**: Popup Builder &#60; 4\.1\.1 \- Popup Status Change via CSRF
**Details**: https://wpscan.com/vulnerability/f0e39557-fe07-4df0-8cc3-4d292f1f545d
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `client-mu-plugins/my-plugin` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/client-mu-plugins/my-plugin))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/hello2` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/hello2))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

## &#x2139;&#xfe0f;&#x20; Obsolete Plugin information
**Plugin Name**: Hello Dolly
**Plugin URI**: https://wordpress.org/plugins/hello-dolly/
**Installed location**: `plugins/subdir1` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/plugins/subdir1))
**Version observed**: 1.6
**Latest version available**: 1.7.2
**Latest version download URI**: https://downloads.wordpress.org/plugin/hello-dolly.1.7.2.zip
***

***Incorrect plugin(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP  [...]

2022-10-06 19:23 UTC, gudmdharalds-a8c commented
# Automated Addon Security Scanning

VIP Code Analysis Bot has identified one or more insecure or obsolete theme(s) being submitted or altered in this pull request. Updating the theme(s) before merging into the target branch is strongly recommended.

***

## &#x2139;&#xfe0f;&#x20; Obsolete Theme information
**Theme Name**: Twenty Twenty\-One
**Theme URI**: https://wordpress.org/themes/twentytwentyone/
**Installed location**: `themes/twentytwentyone` ([view code](https://github.com/gudmdharalds-a8c/vip-go-ci-manual-testing/tree/abfe9c2e0e3b1f5c4ed825df473587ae68984468/themes/twentytwentyone))
**Version observed**: 1.2
**Latest version available**: 1.6
**Latest version download URI**: https://downloads.wordpress.org/theme/twentytwentyone.1.6.zip
***

***Incorrect theme(s)?*** [Learn how to prevent false\-positive matches](https://docs\.wpvip\.com/technical\-references/codebase\-manager/\#h\-preventing\-false\-positive\-plugin\-matches)\.

***

<!-- vip-go-ci-irc-ignore-start -->
This bot provides automated PHP linting and [PHPCS scanning](https://docs.wpvip.com/technical-references/code-review/phpcs-report/). For more information about the bot and available customizations, see [our documentation](https://docs.wpvip.com/technical-references/code-review/vip-code-analysis-bot/).
<!-- vip-go-ci-irc-ignore-end -->


<!-- vip-go-ci-irc-ignore-start -->
<details>
<hr />
<summary>Scan run detail</summary>
<table>
<tr>
<td valign="top" width="40%"><h4>Software versions</h4>
<ul>
<li>vip-go-ci version: <code>1.3.1</code></li>
<li>PHP runtime version for vip-go-ci: <code>8.1.5</code></li>
<li>PHP runtime for linting: 
<ul>
<li>PHP 7.4: <code>7.4.26</code></li>
<li>PHP 8.1: <code>8.1.5</code></li>
</ul></li><li>PHP runtime version for PHPCS: <code>7.4.26</code></li>
<li>PHPCS version: <code>3.7.1</code></li>
<li>PHP runtime version for SVG scanner: <code>8.1.5</code></li>
</ul>
<h4>Options file (<code>.vipgoci_options</code>)</h4>
<p>Options file enabled: 
<code>true</code></p><p>Configurable options:</p>
<ul>
<li><code>skip-execution</code></li><li><code>skip-draft-prs</code></li><li><code>phpcs</code></li><li><code>phpcs-severity</code></li><li><code>phpcs-sniffs-include</code></li><li><code>phpcs-sniffs-exclude</code></li><li><code>review-comments-sort</code></li><li><code>review-comments-include-severity</code></li><li><code>post-generic-pr-support-comments</code></li><li><code>review-comments-sort</code></li><li><code>svg-checks</code></li><li><code>autoapprove</code></li><li><code>autoapprove-php-nonfunctional-changes</code></li></ul>
<p>Options altered:</p>
<ul>
<li>None</li></ul>
</td>
<td valign="top" width="30%">
<h4>PHP lint options</h4>
<p>PHP lint files enabled: 
<code>true</code></p><p>Lint modified files only: 
<code>true</code></p><p>Directories not PHP linted:</p>
<ul>
<li><code>skip-folder-testlint</code></li></ul>
<h4>SVG configuration</h4>
<p>SVG scanning enabled: 
<code>true</code></p><h4>Auto-approval configuration</h4>
<p>Auto-approvals enabled:
<code>true</code></p><p>Non-functional changes auto-approved:
<code>true</code></p><p>Auto-approved file-types:</p>
<ul>
<li><code>css</code></li><li><code>csv</code></li><li><code>eot</code></li><li><code>gif</code></li><li><code>gz</code></li><li><code>ico</code></li><li><code>ini</code></li><li><code>jpg</code></li><li><code>jpeg</code></li><li><code>json</code></li><li><code>less</code></li><li><code>map</code></li><li><code>md</code></li><li><code>mdown</code></li><li><code>mo</code></li><li><code>mp4</code></li><li><code>otf</code></li><li><code>pdf</code></li><li><code>po</code></li><li><code>pot</code></li><li><code>png</code></li><li><code>sass</code></li><li><code>scss</code></li><li><code>styl</code></li><li><code>ttf</code></li><li><code>txt</code></li><li><code>woff</code></li><li><code>woff2</code></li><li><code>yml</code></li></ul>
</td>
<td valign="top" width="30%">
<h4>PHPCS configuration</h4>
<p>PHPCS scanning enabled: 
<code>true</code></p><p>PHPCS severity level: 
<code>1</code></p><p>Standard(s) used:</p>
<ul>
<li><code>WordPress-VIP-Go</code></li><li><code>PHPCompatibilityWP</code></li><li><code>WordPress</code></li></ul>
<p>Runtime set:</p>
<ul>
<li><code>testVersion 7.4-</code></li></ul>
<p>Custom sniffs included:</p>
<ul>
<li>None</li></ul>
<p>Custom sniffs excluded:</p>
<ul>
<li><code>Generic.PHP.Syntax</code></li><li><code>Generic.Commenting.DocComment</code></li><li><code>WordPress.Files.FileName</code></li><li><code>Squiz.Strings.DoubleQuoteUsage</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>Squiz.Commenting.BlockComment</code></li><li><code>Squiz.Commenting.FileComment</code></li><li><code>PEAR.Functions.FunctionCallSignature</code></li></ul>
<p>Directories not PHPCS scanned:</p>
<ul>
<li>None</li></ul>
<h4>WPScan API configuration</h4>
<p>WPScan API scanning enabled: 
<code>true</code></p><p>WPScan API URL: 
<code>https://wpscan.com/api/v3</code></p><p>Directories scanned:</p>
<ul>
<li><code>plugins</code></li><li><code>client-mu-plugins</code></li><li><code>themes</code></li></ul>
<p>Directories not scanned:</p>
<ul>
<li>None</li></ul>
</td>
</tr>
</table>
</details>

<!-- vip-go-ci-irc-ignore-end -->

2022-10-17 12:24 UTC, closed without merging